TRAMITES = {
    "chile": {
        "label": "Chile",
        "tramites": [
            {
                "id": "permiso_trabajo_transitoria",
                "name": "Permiso de Trabajo con Permanencia Transitoria (90 dias)",
                "docs_persona": [
                    "Pasaporte (minimo un ano de vigencia) en PDF",
                    "Poder notarial (debidamente notariado)",
                    "Tarjeta de Turismo (PDI) - legible por ambos lados",
                ],
                "docs_empresa": [
                    "Carta notariada de empresa chilena O Contrato de trabajo con empresa chilena",
                    "Contrato firmado por ambas partes, legalizado por la empresa",
                ],
            },
            {
                "id": "actividades_remuneradas_art17",
                "name": "Actividades Remuneradas Contratado por Empresa Chilena (Art. 17)",
                "docs_persona": [
                    "Pasaporte (minimo un ano de vigencia)",
                    "Certificado de antecedentes penales (apostillado)",
                    "Contrato de trabajo original firmado ante notario",
                    "Fotografia tamano pasaporte (fondo blanco)",
                ],
                "docs_empresa": [
                    "Inicio de actividades o certificado del SII",
                    "Carpeta Tributaria para creditos (menos de 30 dias, PDF)",
                    "Acreditacion de representacion de la persona juridica",
                ],
            },
            {
                "id": "prestacion_servicios_art20",
                "name": "Prestacion de Servicios Cuenta Propia (Art. 20)",
                "docs_persona": [
                    "Pasaporte (minimo un ano de vigencia)",
                    "Certificado de antecedentes penales (apostillado)",
                    "Contrato regulado por derecho civil o comercial",
                    "Especificar funciones y remuneracion",
                ],
                "docs_empresa": [],
            },
            {
                "id": "oferta_trabajo_art18",
                "name": "Oferta de Trabajo (Art. 18)",
                "docs_persona": [
                    "Pasaporte (minimo un ano de vigencia)",
                    "Certificado de antecedentes penales (apostillado)",
                    "Oferta de trabajo protocolizada ante notario",
                    "Carta de aceptacion firmada ante consul chileno",
                ],
                "docs_empresa": [],
            },
            {
                "id": "inversionista_art62",
                "name": "Permiso para Inversionista y Personal Relacionado (Art. 62)",
                "docs_persona": [
                    "Pasaporte (minimo un ano de vigencia)",
                    "Certificado de antecedentes penales (apostillado)",
                    "Carta de patrocinio emitida por InvestChile",
                    "Contrato firmado ante notario",
                    "Contrato extranjero del personal (si aplica, apostillado)",
                ],
                "docs_empresa": [
                    "Inicio de actividades o certificado del SII",
                    "Carpeta Tributaria para creditos (menos de 30 dias, PDF)",
                    "Patente municipal (en algunos casos)",
                    "Acreditacion de representacion legal",
                ],
            },
            {
                "id": "visa_temporal_ex_pede",
                "name": "Visa Temporal Ex Pede",
                "docs_persona": [
                    "Pasaporte",
                    "Certificado de antecedentes penales (apostillado)",
                    "Certificado de permanencia definitiva",
                    "Cedula de identidad (ambos lados)",
                    "Certificado de perdida de permanencia definitiva (PDI online)",
                    "Acreditacion de sustento economico",
                    "Clave unica",
                ],
                "docs_empresa": [
                    "Inicio de actividades o certificado del SII",
                    "Carpeta Tributaria para creditos (menos de 30 dias, PDF)",
                    "Patente municipal (en algunos casos)",
                    "Acreditacion de representacion legal",
                ],
            },
            {
                "id": "permanencia_definitiva",
                "name": "Permanencia Definitiva (PEDE)",
                "docs_persona": [
                    "Fotocopia pasaporte (pagina identificacion y sello de ingreso)",
                    "Cedula de identidad (ambos lados)",
                    "Estampado electronico",
                    "Certificado de antecedentes penales pais de origen (apostillado)",
                    "Certificado de antecedentes penales de Chile",
                    "Certificados historicos AFP e Isapre (ultimos 12 meses)",
                    "Clave unica",
                    "Contrato de trabajo notariado",
                    "Contrato vigente (no mas de 30 dias, notariado con firma electronica)",
                    "Fotografia",
                    "Ultimas 3 liquidaciones de sueldo",
                ],
                "docs_empresa": [],
            },
            {
                "id": "reunificacion_familiar",
                "name": "Reunificacion Familiar",
                "docs_persona": [
                    "Fotocopia pasaporte",
                    "Cedula de identidad del familiar",
                    "Certificado de antecedentes penales (solo adultos)",
                    "Ultima tarjeta de turismo (menores, si se tramita en Chile)",
                    "Fotografia tamano pasaporte",
                    "Resolucion exenta de permanencia definitiva",
                    "Declaracion jurada de gastos (original, notariada)",
                    "Para conyuge: Certificado de matrimonio original (apostillado)",
                    "Para hijos: Certificado de nacimiento original (apostillado)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "visto_consular_turismo",
                "name": "Visto Consular de Turismo (VCT)",
                "docs_persona": [
                    "Pasaporte vigente o vencido desde 2013",
                    "Formulario SAC completo",
                    "Fotografia color fondo blanco 5x5cm",
                    "Reserva de hotel o carta de invitacion notariada",
                    "Acreditacion de residencia (si es diferente a nacionalidad)",
                    "Comprobante de ingresos (3 ultimas liquidaciones y/o extractos bancarios)",
                    "Certificado de antecedentes penales (apostillado, 60 dias vigencia)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "mercosur_reciprocidad",
                "name": "MERCOSUR Reciprocidad Internacional",
                "docs_persona": [
                    "Pasaporte o documento de identidad (minimo un ano vigencia)",
                    "Certificado de antecedentes penales (pais origen o residencia ultimos 5 anos, adultos)",
                ],
                "docs_empresa": [],
            },
        ],
    },
    "espana": {
        "label": "Espana",
        "tramites": [
            {
                "id": "convenio_bilateral_ss",
                "name": "Convenio Bilateral Seguridad Social Chile-Espana",
                "docs_persona": [
                    "Contrato de trabajo",
                    "Ultimas 3 liquidaciones de sueldo",
                    "Ultimas 3 cotizaciones previsionales (Previred)",
                    "Anexo al contrato de trabajo (modelo Tramilex)",
                    "Carta tramitador (modelo Tramilex)",
                    "Cedula de identidad del tecnico desplazado",
                    "Nombres de los padres (Filiacion)",
                    "Datos empresa receptora en Espana (Nombre, CIF, direccion)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "desplazamiento_ict_ue",
                "name": "Desplazamiento Intraempresarial ICT UE",
                "docs_persona": [
                    "Cedula de identidad (ambos lados)",
                    "Contrato de trabajo",
                    "Anexo de desplazamiento",
                    "Ultimas 12 cotizaciones provisionales (Previred)",
                    "Autorizacion para tramitacion (prepara Tramilex)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "traslado_ict_ue",
                "name": "Traslado Intraempresarial ICT UE (General)",
                "docs_persona": [
                    "Pasaporte completo o documento de viaje valido",
                    "Contrato de trabajo chileno y anexo de desplazamiento",
                    "Ultimas 3 liquidaciones de sueldo",
                    "Seguro medico publico o privado en Espana",
                    "Certificado de cobertura de Seguridad Social (si existe convenio)",
                    "Justificante pago tasa correspondiente",
                    "CV del trabajador",
                    "Titulo de educacion superior o certificacion de 3 anos experiencia",
                    "Acreditacion relacion laboral minimo 3 meses con empresa del grupo",
                ],
                "docs_empresa": [
                    "Documento publico de representacion legal y DNI/NIE del representante",
                    "Copia NIF empresa receptora y prueba de actividad en Espana",
                    "Certificado al corriente TGSS y Hacienda (menos de 30 dias)",
                    "Acreditacion grupo de empresas o contrato de prestacion de servicios",
                    "Carta empresa extranjera detallando actividades, motivo, periodo, salario",
                ],
            },
            {
                "id": "nomada_digital",
                "name": "Nomada Digital (Teletrabajadores Internacionales)",
                "docs_persona": [
                    "Pasaporte completo (todas las paginas)",
                    "Justificante pago tasa (mod. 790 038)",
                    "Formulario MIT firmado (prepara Tramilex)",
                    "Acreditacion relacion laboral minimo 3 meses con empresa extranjera",
                    "Ultimas 3 liquidaciones de sueldo",
                    "Acreditacion actividad real empresa (minimo 1 ano)",
                    "Certificado antiguedad laboral y cotizaciones pais de origen",
                    "Carta empresa autorizando trabajo remoto desde Espana",
                    "Anexo al contrato",
                    "Titulo o experiencia minima 3 anos en el puesto",
                    "Certificado cobertura Seguridad Social o compromiso alta en SS espanola",
                    "Certificado antecedentes penales (ultimos 2 anos) + declaracion jurada 5 anos",
                    "Seguro medico publico o privado (no se acepta seguro de viaje)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "cuenta_ajena_inicial",
                "name": "Cuenta Ajena Inicial (Permiso Trabajo por Cuenta Ajena)",
                "docs_persona": [
                    "Pasaporte completo (todas las paginas)",
                    "Contrato firmado por empleador y trabajador",
                    "Certificaciones de formacion o experiencia (apostilladas)",
                    "CV del trabajador",
                ],
                "docs_empresa": [
                    "Copia escrituras de constitucion de la empresa",
                    "Poderes si no constan en escrituras",
                    "DNI administrador (ambos lados)",
                    "CIF definitivo",
                    "Certificado inscripcion empresa en TGSS",
                    "Certificado al corriente Hacienda",
                    "Certificado al corriente TGSS",
                    "Modelos Hacienda ultimo ano (303, 111)",
                    "Ultima declaracion Impuesto de Sociedades (modelo 200)",
                    "Informe de vida laboral empresa (VILE)",
                    "Informe descriptivo firmado",
                    "Designacion de representante",
                    "Formulario X-03 (rellena Tramilex)",
                    "Pago de tasas",
                ],
            },
            {
                "id": "renovacion_cuenta_ajena",
                "name": "Renovacion de Residencia por Cuenta Ajena",
                "docs_persona": [
                    "Pasaporte completo o documento de viaje (copia ambos lados)",
                    "Tarjeta de Residencia (ambos lados)",
                    "Contrato de trabajo vigente (si cambio de empleador)",
                    "Acreditacion actividad laboral minimo 3 meses por ano autorizado",
                ],
                "docs_empresa": [],
            },
            {
                "id": "prestaciones_transnacionales",
                "name": "Residencia Temporal - Prestaciones Transnacionales de Servicios",
                "docs_persona": [
                    "Pasaporte completo (escaneado PDF)",
                    "Contrato firmado por empleador y trabajador",
                    "Certificaciones formacion o experiencia (apostilladas)",
                    "CV del trabajador",
                ],
                "docs_empresa": [
                    "Certificado inscripcion empresa en TGSS",
                    "Certificado al corriente Hacienda y TGSS",
                    "Copia escrituras de constitucion",
                    "CIF",
                    "Acreditacion solvencia: IRPF, IVA, Impuesto Sociedades o informe VILE",
                    "Informe descriptivo del puesto (prepara Tramilex)",
                    "DNI administrador",
                    "Formulario X-03 (rellena Tramilex)",
                    "Pago de tasas",
                ],
            },
            {
                "id": "golden_visa",
                "name": "Golden Visa (Residencia para Inversores)",
                "docs_persona": [
                    "Pasaporte",
                    "Seguro medico publico o privado",
                    "Certificado antecedentes penales",
                    "Acreditacion de la inversion realizada",
                    "Acreditacion medios economicos suficientes (4x IPREM titular, 1x IPREM por familiar)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "residencia_cuenta_propia",
                "name": "Residencia Temporal y Trabajo por Cuenta Propia",
                "docs_persona": [
                    "Formulario EX-07 por duplicado",
                    "Pasaporte completo o documento de viaje",
                    "Declaracion responsable o comunicacion previa (actividades comercio minorista)",
                    "Listado autorizaciones/licencias necesarias",
                    "Acreditacion cualificacion profesional (homologacion si procede)",
                    "Acreditacion inversion suficiente e impacto en creacion empleo",
                ],
                "docs_empresa": [],
            },
            {
                "id": "visa_familiar_comunitario",
                "name": "Visa de Familiar de Comunitario",
                "docs_persona": [
                    "Formulario X-19 por duplicado firmado",
                    "Pasaporte valido del familiar",
                    "Acreditacion vinculo familiar con ciudadano UE/EEE",
                    "DNI ciudadano espanol o certificado registro ciudadano UE",
                    "Empadronamiento conjunto de toda la unidad familiar",
                    "Certificados antecedentes penales (apostillados)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "visado_estudiante",
                "name": "Visado de Estudiante",
                "docs_persona": [
                    "Formulario de solicitud EX00 firmado",
                    "Acreditacion medios economicos para el periodo solicitado",
                    "Acreditacion seguro medico",
                    "Carta de admision o matricula del centro de estudios",
                    "Certificado medico (si duracion superior a 6 meses)",
                    "Certificado antecedentes penales (si mayor de edad, ultimos 5 anos)",
                ],
                "docs_empresa": [],
            },
            {
                "id": "modificacion_estancia",
                "name": "Modificacion de Estancia de Visado (Estudiante a Trabajo)",
                "docs_persona": [
                    "Acreditacion aprovechamiento de estudios",
                    "Pasaporte completo (todas paginas, PDF)",
                    "CV del trabajador",
                    "Designacion de representante (prepara Tramilex)",
                    "Copia NIE",
                ],
                "docs_empresa": [
                    "Contrato firmado por empleador y trabajador",
                    "Certificado inscripcion empresa en TGSS (actualizado)",
                    "Certificado al corriente Hacienda y TGSS (actualizado)",
                    "Copia escrituras de constitucion",
                    "CIF empresa",
                    "Acreditacion solvencia: IRPF, IVA, Impuesto Sociedades o VILE",
                    "Informe descriptivo del puesto (prepara Tramilex)",
                    "DNI administrador",
                    "Formulario X-03 (rellena Tramilex)",
                    "Pago de tasas",
                ],
            },
            {
                "id": "recuperacion_residencia",
                "name": "Recuperacion Residencia de Larga Duracion",
                "docs_persona": [
                    "Formulario EX-11 por duplicado",
                    "Pasaporte o documento de viaje (minimo 4 meses vigencia)",
                    "Certificado antecedentes penales (ultimos 5 anos)",
                    "Certificado medico",
                ],
                "docs_empresa": [],
            },
            {
                "id": "arraigo_familiar",
                "name": "Arraigo Familiar (Circunstancias Excepcionales)",
                "docs_persona": [
                    "Formulario EX-10 por duplicado (prepara Tramilex)",
                    "Pasaporte completo (todas las paginas)",
                    "Certificado antecedentes penales (5 anos previos a entrada en Espana)",
                    "Para padres de menor espanol: Certificado nacimiento del menor (nacionalidad espanola y vinculo familiar)",
                    "Para conyuges: Certificado nacimiento del hijo que otorga el derecho",
                ],
                "docs_empresa": [],
            },
        ],
    },
}


def get_tramites_by_country(country):
    data = TRAMITES.get(country, {})
    if not data:
        return []
    return [{"id": t["id"], "name": t["name"]} for t in data.get("tramites", [])]


def get_tramite_docs(country, tramite_id):
    data = TRAMITES.get(country, {})
    for t in data.get("tramites", []):
        if t["id"] == tramite_id:
            return {
                "id": t["id"],
                "name": t["name"],
                "docs_persona": t.get("docs_persona", []),
                "docs_empresa": t.get("docs_empresa", []),
            }
    return None
